name: Vet

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: nrkno/yaml-schema-validator-github-action@v5
        with:
          schema: schema.yaml
          target: endpoints
